Controllers/TimeEntryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Security.Claims;


using TimeReportProject.Models;
using TimeReportProject.Repository;
using TimeReportProject.ViewModels;

namespace TimeReportProject.Controllers
{
    public class TimeEntryController : Controller
    {
        private IProjects _project;
        private IConsultantSchedule _consultantSchedule;
        private IUsers _users;
        public TimeEntryController(IProjects project, IConsultantSchedule consultantschedule,IUsers users)
        {
            _project = project;
            _consultantSchedule = consultantschedule;
            _users = users;

        }
      
        [HttpGet]
        public IActionResult EnterTimeDetails()
        {
            ConsultantProjectViewModel model = new ConsultantProjectViewModel();

            model.ID = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            //Find the Name of the consultant.
            model.ConsultantName = _consultantSchedule.GetConsultantNameByID(model.ID);
            model.ProjectList = _project.GetProjectForList();
            return View(model);

        }
        [HttpPost]
        public IActionResult EnterTimeDetails(ConsultantProjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                ConsultantProject consultantProject = new ConsultantProject();

                consultantProject.UserID = model.ID;
                consultantProject.ProjectID = model.ProjectID;
                consultantProject.EntryDate = model.EntryDate;

               
                consultantProject.StartTime = model.StartTime;
                consultantProject.EndTime = model.EndTime;
               
                consultantProject.StartLunchTime = model.StartLunchTime;
               
                consultantProject.EndLunchTime = model.EndLunchTime;
                consultantProject.Comments = model.Comments;
                var result = _consultantSchedule.AddScheduleDetails(consultantProject);
                if (result == true)
                    ViewBag.Message = "The schedule details have been updated";
                else
                {
                    ViewBag.Message = "Error occured while adding the time details.";
                    //ViewBag.Message = _consultantSchedule.ErrorMessage;
                    //return View("Error");
                }
            }
            model.ProjectList = _project.GetProjectForList();
            return View(model);

        }

        [HttpGet]
        public IActionResult MonthWiseDetails(int? pageNo)
        {
            MonthWiseViewModel monthwisedetails = new MonthWiseViewModel();
            monthwisedetails.Projects = _project.GetProjectForList();
            monthwisedetails.Users = _users.GetUsersForDropDown();
            monthwisedetails.Months = FillMonthData();
            monthwisedetails.Years = FillYearData();

          
            return View(monthwisedetails);

        }
        public List<SelectListItem > FillYearData()
        {
            List<SelectListItem> yearList = new List<SelectListItem>();
            Dictionary<int, int> Years = new Dictionary<int, int>();
            for(int i= 2040; i>=2000;i--)
                Years.Add(i,i);
            yearList.AddRange(Years.Select(keyValuePair => new SelectListItem()
            {
                Value = keyValuePair.Value.ToString(),
                Text = keyValuePair.Key.ToString()
            }));

            SelectListItem item2 = new SelectListItem();
            item2.Text = "Select the Year";
            item2.Value = "";
            item2.Selected = true;
            yearList .Insert(0, item2);


            return yearList;    
        }
        public List<SelectListItem > FillMonthData()
        {
            //Months List
            Dictionary<string, int> monthNames = new Dictionary<string, int>();
            monthNames.Add("January", 1);
            monthNames.Add("February", 2);
            monthNames.Add("March", 3);
            monthNames.Add("April", 4);
            monthNames.Add("May", 5);
            monthNames.Add("June", 6);
            monthNames.Add("July", 7);
            monthNames.Add("August", 8);
            monthNames.Add("September", 9);
            monthNames.Add("October", 10);
            monthNames.Add("November", 11);
            monthNames.Add("December", 12);
            List<SelectListItem> Mnames = new List<SelectListItem>();

            Mnames.AddRange(monthNames.Select(keyValuePair => new SelectListItem()
            {
                Value = keyValuePair.Value.ToString(),
                Text = keyValuePair.Key
            }));
            

            SelectListItem item2 = new SelectListItem();
            item2.Text = "Select the Month";
            item2.Value = "";
            item2.Selected = true;
            Mnames.Insert(0, item2);
            return Mnames;
        }
      


        [HttpPost]
        public IActionResult MonthWiseDetailsSearch(int? ProjectId,int? MonthID,int? YearID,string? userId, int? pageNo)
        {
            MonthWiseViewModel monthwisedetails = new MonthWiseViewModel();
            monthwisedetails.MonthWise = _consultantSchedule.GetMonthWiseDetails(ProjectId , MonthID,YearID, userId);

            //include the logic for pagination
            int pageSize = 10;
            int PNo;
            PNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            int skip = (PNo - 1) * pageSize;
            var totalRecords = monthwisedetails.MonthWise.Count();
            monthwisedetails.MonthWise = monthwisedetails.MonthWise.Skip(skip).Take(pageSize).ToList();
            monthwisedetails.Pager = new Pager(totalRecords, PNo, pageSize);
            monthwisedetails.Projects = _project.GetProjectForList();
            monthwisedetails.Users = _users.GetUsersForDropDown();
            monthwisedetails.Months = FillMonthData();
            monthwisedetails.Years = FillYearData();
            monthwisedetails.MonthID = MonthID;
            monthwisedetails.YearID = YearID;
            monthwisedetails.UserID = userId;
            monthwisedetails.ProjectID = ProjectId;

            return View("MonthWiseDetails", monthwisedetails);

        }
        public IActionResult DateWiseDetails()
        {
            DayWiseViewModel model = new DayWiseViewModel();
            model.Months = FillMonthData();
            model.Users = _users.GetUsersForDropDown();
           
            return View(model);

        }

        [HttpPost]
        public IActionResult DateWiseDetails( string? UserId,int? MonthID,DateTime? ScheduleDate,int? pageNo)
        {
            DayWiseViewModel model = new DayWiseViewModel();
            
            //include the logic for pagination
            int pageSize = 10;
            int PNo;
            int YearID;
            YearID = DateTime.Now.Year; // the report is for the current financial year.

            PNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            int skip = (PNo - 1) * pageSize;
            model.DayWiseDetails = _consultantSchedule.GetDateWiseDetails(UserId, MonthID,YearID, ScheduleDate);
            var totalRecords = model.DayWiseDetails .Count();
            model.DayWiseDetails  = model.DayWiseDetails.Skip(skip).Take(pageSize).ToList();
            model.Months = FillMonthData();
            model.Users = _users.GetUsersForDropDown();
            model.Pager = new Pager(totalRecords, PNo, pageSize);
            return View(model);

        }

    }
}
//string STime, ETime, SLTime, ELTime;
//STime = Convert.ToDateTime(model.StartTime).ToString("HH:mm");
//ETime = Convert.ToDateTime(model.EndTime).ToString("HH:mm");
//SLTime = Convert.ToDateTime(model.StartLunchTime).ToString("HH:mm");
//ELTime = Convert.ToDateTime(model.EndLunchTime).ToString("HH:mm");
// STime = String.Format(Convert.ToDateTime(model.StartTime).Hour.ToString(),"00") + ":" + String.Format(Convert.ToDateTime(model.StartTime).Minute.ToString(),"00");
//ETime = String.Format(Convert.ToDateTime(model.EndTime).Hour.ToString(),"00") + ":" + String.Format(Convert.ToDateTime(model.EndTime).Minute.ToString(),"00");



//@if(Model.ShowRequestId)
//{
//    < p >
//        < strong > Request ID:</ strong > < code > @Model.RequestId </ code >

//       </ p >
//}

// //data:$('#projectform').serialize() is used to pass the modal data to the controller, but as I had to pass the page no also, I
//could not see how to pass Modal data and the pageNo, so I used diff variables to be passing the val() of the dropdown list to the controller.

Views/TimeEntry/DateWiseDetails.cshtml
@model TimeReportProject.ViewModels.DayWiseViewModel  
<div id=displayresults>
<div class="container" style="padding-top:50px">
    <div class="row">
        <div class="panel panel-default">

            <div class="panel-heading text-center">
                
                <div class="panel-title">Consultant wise time report (For the current financial year)</div>
            </div>

            <div class="panel-body">
                @if(Model.Users.Count>1)
                    {
                    <form id="projectform" method="post" asp-action="DateWiseDetails" asp-controller="TimeEntry">
                   <div class="row">
                     <div class="col-lg-12">
                        <div id="div1" runat="server" class="panel panel-primary">
                           <div class="panel-heading text-center" style="padding:0px;">Options</div>
                             <div class="panel-body">
                                <div class="row">
                                       <div class="col-lg-2">@Html.Label("UserID", "Consultant Name", new { @class = "form-control-static" })</div>
                                       <div class="col-lg-4">@Html.DropDownListFor(x => x.UserID , Model.Users , new { @class = "form-control dropdown input-sm", @id="UserID"})</div>
                                      
                                </div>                          
                                <div class=row>
                                    <div class="col-lg-2">@Html.Label("MonthID", "For the month", new { @class = "form-control-static" })</div>
                                    <div class="col-lg-4">@Html.DropDownListFor(x => x.MonthID , Model.Months, new { @class = "form-control dropdown input-sm",@id = "MonthID"  })</div>
                                 
                                    <div class="col-lg-2">@Html.Label("ScheduleDate", "For the date", new { @class = "form-control-static" })</div>
                                   <div class="col-lg-2">
                                   @Html.TextBoxFor(model => model.ScheduleDate , new { @class = "form-control input-sm", @maxlength = "10" ,@id="ScheduleDate"})
                                   </div>
                                </div>
                                <div class=row>
                                    <div class="col-lg-12  text-center">
                                         <button id="btnSearch" type="submit" class="btn btn-sm btn-primary">Search</button>

 
                                    </div>
                                </div>
                                
                                
                            </div>
                        </div>
                     </div>
                   </div>
               </form> 
                        
                    }
                    else

                    {
                  
                    <div class="row">
                        <div class="col-lg-10">
                           <h6 style="color:maroon">Consultant details not available.</h6>
                        </div>

                     </div>
                  
                    }

                
                
                @if(Model.DayWiseDetails!=null)
                { @if(Model.DayWiseDetails.Count>0)
               {
                        <div class=row>
                            <div class=col-lg-12>
                                <table id= "datewisetable" class="table  table-bordered  table-condensed table-fixedhead">
                                    <thead class="bg-primary" style="font-size:12px">
                                        <tr><td>Project</td><td>Date</td><td>Working Hours</td><td>Lunch Time</td><td>Comments</td></tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var detail in Model.DayWiseDetails)
                                        {
                                            <tr style="font-size:12px">
                                              <td width=20%>@detail.Project.ProjectName </td>
                                                <td width=10%>@String.Format("{0:d}",@detail.EntryDate )</td>
                                                <td width=15%>@String.Format("{0:hh:mm tt}",@detail.StartTime) - @String.Format("{0:hh:mm tt}",@detail.EndTime)   </td>
                                               
                                                <td width=15%> @String.Format("{0:hh:mm tt}",@detail.StartLunchTime) - @String.Format("{0:hh:mm tt}",@detail.EndLunchTime)
 
                                                 </td>
                                               <td wdith=40%>@detail.Comments </td>
                               
                                            </tr>

                                         }

                                 </tbody>
                             </table>
               
                 </div>
               </div>
                <nav id= "navpage" aria-label="Page navigation example">
           <ul class="pagination justify-content-center d-flex flex-wrap">
            @if (Model.Pager.CurrentPage > 1)
            {
             
                <li class="page-item">
                     <a href="#" class="page-link" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</a>
                   
                </li>
            }
             @if (Model.Pager.StartPage != Model.Pager.EndPage)
              {
               @for (var p = Model.Pager.StartPage; p <= Model.Pager.EndPage; p++)
               {
                <li class="page-item @(p == Model.Pager.CurrentPage ? "active" : "")">
                    <a class="page-link" href="#" data-pageno="@p">@p</a>
                </li>
               }
             }
            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <li class="page-item">
                   <a class="page-link" href="#" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</a>
                </li>
              
            }
          </ul>     
        </nav>
      
                }
                else
                {
                  
                    <div class="row">
                        <div class="col-lg-10">
                           <h6 style="color:maroon">No records found for the Report.</h6>
                        </div>

                     </div>
                  
                }

                    
                }
               
            </div>
        </div>

    </div>
</div>
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () 
        {

             $(document).on("click", '.pagination >li', function (e) {
                var pageNo = $(this).find('a').attr("data-pageNo");
                $.ajax({
                url: '@Url.Action("DateWiseDetails", "TimeEntry")',
                type: "POST",
                data: {
                   UserId : $("#UserID").val(),
                   MonthID: $("#MonthID").val(),
                   ScheduleDate : $("#ScheduleDate").val(),
                    pageNo: pageNo
                    
                }
                
            }).success(function (response) {
                     
                      $("#displayresults").html(response);
                   })
                  .done(function (response) {

                  })

                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("FAIL");
                })
            });

      


        $("[id$=ScheduleDate]").datepicker({
            showOn: 'focus',
            dateFormat: 'mm/dd/yy'
        });
        $('#btnSearch').click(function()
        {
          const dateS = $("#ScheduleDate").val();
          const MonthN = $("#MonthID").val();
          if($("#UserID").val() == "")
           {
               alert("Select the Consultant Name");
               $("#datewisetable").empty();
               $("#navpage").empty();
               return false;
           }
          if(dateS == "" && MonthN == "")
          {
              alert("Select atleast one of the values : (Month Name/Date)");
              $("#datewisetable").empty();
              $("#navpage").empty();
              return false;
          }
        });
    })
    </script>
}

Views/TimeEntry/EnterTimeDetails.cshtml
@model TimeReportProject.ViewModels.ConsultantProjectViewModel
<div class="container" style="padding-top:50px">
    <div class="row">
        <div class="panel panel-default">

            <div class="panel-heading text-center">

                <div class="panel-title"> Enter the Time Details</div>
            </div>

            <div class="panel-body">
                <form id="timeentryform" method="post" asp-controller="TimeEntry" asp-action="EnterTimeDetails">
                    <input hidden value= "@Model.ID" name="ID" id="ID" />

                    <div class="row bottom bottom-buffer-small">
                        <div class="col-lg-2"> @Html.Label("ConsultantName", "Consultant Name", new { @class = "form-control-static" })</div>
                        <div class="col-lg-6"> @Html.TextBoxFor(model => model.ConsultantName, new { @class = "form-control input-sm", @readonly = "readonly" })</div>

                    </div>
                    <div class="row bottom">

                        <div class="col-lg-2">@Html.Label("EntryDate", "Reporting Date", new { @class = "form-control-static" })</div>
                        <div class="col-lg-2">
                        @Html.TextBoxFor(model => model.EntryDate, new { @class = "form-control input-sm", @maxlength = "10" ,@id="EntryDate"})
                        @*@Html.ValidationMessageFor(model => model.EntryDate , "", new {@class = "text-danger validation-message"})*@
                        </div>
                       
                    </div>
                    <div class="row">
                        <div class="col-lg-2">@Html.Label("ProjectName", "Project Name", new { @class = "form-control-static" })</div>
                        <div class="col-lg-4">@Html.DropDownListFor(x => x.ProjectID, Model.ProjectList, new { @class = "form-control dropdown input-sm" })</div>
                        @*@Html.ValidationMessageFor(model => model.ProjectID,"", new {@class = "text-danger validation-message"})*@
                    </div>
                    <div class="row bottom">
                        <div class="col-lg-2">@Html.Label("StartTime", "Working Hours", new { @class = "form-control-static" })</div>
                        <div class="col-lg-2">
                            @Html.TextBoxFor(model => model.StartTime, new { @class = "form-control input-sm", @maxlength = "7", @id = "StartTime"  })
                            @*@Html.ValidationMessageFor(model => model.StartTime ,"", new {@class = "text-danger validation-message"})*@
                        </div>
                        <div class="col-lg-1">-</div>

                        <div class="col-lg-2">
                           @Html.TextBoxFor(model => model.EndTime, new { @class = "form-control input-sm", @maxlength = "7", @id = "EndTime"})
                           @*@Html.ValidationMessageFor(model => model.EndTime,"", new {@class = "text-danger"})*@
                        </div>

                    </div>
                    <div class="row bottom">
                        <div class="col-lg-2">@Html.Label("StartLunchTime", "Lunch Time", new { @class = "form-control-static" })</div>
                        <div class="col-lg-2">@Html.TextBoxFor(model => model.StartLunchTime, new { @class = "form-control input-sm", @maxlength = "7", @id = "SLunchTime" })</div>
                        @*@Html.ValidationMessageFor(model => model.StartLunchTime,"", new {@class = "text-danger"})*@
                        <div class="col-lg-1">-</div>
                        <div class="col-lg-2">@Html.TextBoxFor(model => model.EndLunchTime, new { @class = "form-control input-sm", @maxlength = "7", @id = "ELunchTime"})</div>
                        @*@Html.ValidationMessageFor(model => model.EndLunchTime ,"", new {@class = "text-danger"})*@
                    </div> 
                     <div class="row bottom">
                        <div class="col-lg-2">@Html.Label("Comments", "Additional Information", new { @class = "form-control-static" })</div>
                        <div class="col-lg-6">@Html.TextBoxFor(model => model.Comments , new { @class = "form-control input-sm", @maxlength = "100", @id = "Comments" })</div>
                       
                    </div> 
                   
                    <div class="row bottom">
                        <div class="col-lg-12">
                            @Html.ValidationSummary(false, "", new { @class = "alert-danger"})
                        </div>
                    </div>
                    <div class="row bottom bottom-buffer-small">
                        <div class="col-lg-12 text-center">
                            <button id="btnSave" type="submit" class="btn btn-sm btn-primary" >Save Details</button>

                        </div>
                    </div>
                    <div class= "row bottom">
                        <div class="col-lg-12">
                            <h6 style="color:maroon">@ViewBag.Message</h6>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        function convertTime(timeStr)
    {
      const [time, modifier] = timeStr.split(' ');
          let [hours, minutes] = time.split(':');
         
          if (hours == '12')
          {
           hours = '00';
          }
         if (modifier == 'PM')
          {
           hours = parseInt(hours) + 12;
         
          }
         return (parseInt(hours*60) + parseInt(minutes));
    }

        $(document).ready(function () {
             $('#btnSave').click(function()
         {
        const timeS = $("#SLunchTime").val();
        const timeE = $("#ELunchTime").val();
        const timeStart = $("#StartTime").val();
        const timeEnd = $("#EndTime").val();
        if (timeStart != "" && timeEnd == "")
        {  
          alert("Enter the End time");
         // $("[id$=EndTime]").focus();
          return false;
        }
        if (timeEnd !="" && timeStart =="")
        {
            alert("Enter the Start time");
           // $("[id$=StartTime]").focus();
            return false;
        }
         if (timeS != "" && timeE == "")
        {  
          alert("Enter the Lunch end time");
          //$("[id$=ELunchTime]").focus();
          return false;
        }
        if (timeE !="" && timeS == "")
        {
            alert("Enter the Lunch start time");
            //$("[id$=SLunchTime]").focus();
            return false;
        }
        if (convertTime(timeStart) >= convertTime(timeEnd))
        {
      
           alert("From time cannot be greater than the To Time");
           return false;
        }

        if (convertTime(timeS)>=convertTime(timeE))
        {
          alert("Lunch From time cannot be greater than the Lunch To Time");
          return false;
        }
       });
  

        $("[id$=EntryDate]").datepicker({
            showOn: 'focus',
            dateFormat: 'mm/dd/yy'
        });
        $("[id$=StartTime]").timepicker({
            timeFormat: 'h:mm p',
            interval: 10,
            minTime: '8:00am',
            maxTime: '5:00pm',
            showDuration:true,
            //startTime: '8:00am',
            dynamic:false,
            dropdown: true,
            scrollbar: true,
             showOn:'focus'
        });
        $("[id$=EndTime]").timepicker({
            timeFormat: 'h:mm p',
            interval: 10,
            minTime: '8:00am',
	        maxTime: '05:00pm',
	        showDuration: true,
            dynamic:false,
            dropdown: true,
            scrollbar: true,
            showOn:'focus'
        });
        $("[id$=SLunchTime]").timepicker({
            timeFormat: 'h:mm p',
            interval: 10,
            minTime: '8:00am',
            maxTime: '5:00pm',
            showDuration:true,
            dynamic: false,
            dropdown: true,
            scrollbar: true,
             showOn:'focus'
        });
         $("[id$=ELunchTime]").timepicker({
            timeFormat: 'h:mm p',
            interval: 10,
            minTime: '8:00am',
            maxTime: '5:00pm',
            showDuration:true,
            dynamic: false,
            dropdown: true,
            scrollbar: true,
             showOn:'focus'
        });
      

    })

  
    </script>
    }